---
# Check if gem is already installed
- name: "Check if ${item} is installed"
  command: gem list ${item} -i
  ignore_errors: True
  register: gem_installed
  tags:
    - kibana

# Install gem
- name: "Install gem: ${item}"
  command: gem install ${item}
  only_if: "'${gem_installed.stdout}' == 'false'"
  tags:
    - kibana
