---
- name: 'Install kibana from git repository'
  get_url: url={{ kibana.url }} dest={{ kibana.temp_file }}

- name: 'Create kibana install directory'
  file: path={{ kibana.dir }} owner=root group=root mode=0755 state=directory

- name: 'Unzip kibana release to install directory'
  command: unzip -u {{ kibana.temp_file }} -d {{ kibana.dir }}

- name: 'symlink install directory to webroot'
  file: src={{ kibana.dir}}/kibana-latest dest={{kibana.webroot}} state=link

- name: 'Create Nginx site for kibana'
  include: ../../nginx/tasks/site.yml
  template: roles/kibana/template/kibana.j2
  vars:
    site: kibana